#!/usr/bin/python3
"""
"""
import unittest
import models
from datetime import datetime
from models.base_model import baseModel

class testBaseModel(unittest.TestCase):
    """

    """
    def test_no_arg(self):
        self.assertEqual(BaseModel(), type(BaseModel()))
    
    def test_instance(self):
        self.assertIsInstance(BaseModel(), )
